version: '2'
services:
  mongo:
    image: mongo:3
    volumes:
    - /var/lib/graylog/data/mongo:/data/db
    logging:
      driver: syslog
      options:
        tag: graylog-mongo
    labels:
      io.rancher.container.hostname_override: container_name
  elasticsearch:
    image: elasticsearch:2
    volumes:
    - /var/lib/graylog/data/elasticsearch:/usr/share/elasticsearch/data
    logging:
      driver: syslog
      options:
        tag: graylog-elasticsearch
    command:
    - elasticsearch
    - -Des.cluster.name=graylog
    labels:
      io.rancher.container.hostname_override: container_name
  graylog:
    image: graylog2/server:2.1.0-3
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_WEB_ENDPOINT_URI: ${GRAYLOG_WEB_ENDPOINT_URI}
    volumes:
    - /var/lib/graylog/data/journal:/usr/share/graylog/data/journal
    - /var/lib/graylog/config:/usr/share/graylog/data/config
    logging:
      driver: syslog
      options:
        tag: graylog-server
    links:
    - elasticsearch:elasticsearch
    - mongo:mongo
    ports:
    - 9000:9000/tcp
    - 1514:1514/udp
    - 12201:12201/udp
    - 514:514/tcp
    - 514:514/udp
    labels:
      io.rancher.container.hostname_override: container_name
