---
# This playbook install nfs client on servers and mounts an central nfs share
- hosts: '{{ hosts }}' 
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Updating system
      apt: 
        update_cache: yes

    - name: Install nfs-common
      apt:
        name: nfs-common
        state: present

    - name: Create target directory
      file:
        path: '{{ target }}' 
        state: directory
        mode: 0755

    - name: Installing and mounting share
      mount:
        name: '{{ target }}'
        src: '{{ share }}'
        fstype: nfs
        state: mounted
