version: '2'
catalog:
  name: Registry
  version: 2
  description: Official Docker Registry (see more on docs.docker.com/registry/)
services:
  registry:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 5000
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
      reinitializing_timeout: 60000
